// <auto-generated />
using System;
using Gorjanc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gorjanc.Migrations
{
    [DbContext(typeof(GorjancContext))]
    partial class GorjancContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gorjanc.Models.Obisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("OsebaId")
                        .HasColumnType("int");

                    b.Property<int>("VrhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OsebaId");

                    b.HasIndex("VrhId");

                    b.ToTable("Obisk");
                });

            modelBuilder.Entity("Gorjanc.Models.Oseba", b =>
                {
                    b.Property<int>("OsebaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priimek")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OsebaId");

                    b.ToTable("Oseba");
                });

            modelBuilder.Entity("Gorjanc.Models.Slika", b =>
                {
                    b.Property<int>("SlikaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumSlike")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Img")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("VrhId")
                        .HasColumnType("int");

                    b.HasKey("SlikaId");

                    b.HasIndex("VrhId");

                    b.ToTable("Slika");
                });

            modelBuilder.Entity("Gorjanc.Models.Vrh", b =>
                {
                    b.Property<int>("VrhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Koordinate")
                        .HasColumnType("float");

                    b.Property<int>("Visina")
                        .HasColumnType("int");

                    b.HasKey("VrhId");

                    b.ToTable("Vrh");
                });

            modelBuilder.Entity("Gorjanc.Models.Obisk", b =>
                {
                    b.HasOne("Gorjanc.Models.Oseba", null)
                        .WithMany("Obiskani")
                        .HasForeignKey("OsebaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorjanc.Models.Vrh", null)
                        .WithMany("Obiskani")
                        .HasForeignKey("VrhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gorjanc.Models.Slika", b =>
                {
                    b.HasOne("Gorjanc.Models.Vrh", null)
                        .WithMany("Slika")
                        .HasForeignKey("VrhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
